name: Bump Version & Release

on:
  push:
    branches:
    - main

jobs:
  bump:
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: [self-hosted]
    name: Bump version, update changelog
    permissions:
      id-token: write
      contents: write
    outputs:
        TAG_VERSION: ${{ steps.version.outputs.TAG_VERSION }}

    steps:

    - uses: actions/checkout@v3
      name: Check out
      with:
        token: "${{ secrets.PERSONAL_TOKEN }}"
        fetch-depth: 0
    - uses: actions/setup-python@v3
      name: Set up Python
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements-ci.txt'
    - name: Create bump and changelog
      id: version
      run: |
        git config --global user.email ""
        git config --global user.name "GitHub Actions"
        pip install --upgrade pip -q
        pip install -r requirements-ci.txt -q
        cz bump --changelog
        git push --follow-tags
        echo "TAG_VERSION=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

  release:
    runs-on: [self-hosted]
    needs: bump
    permissions:
      id-token: write
      contents: write

    steps:

    - uses: softprops/action-gh-release@v1
      name: Release
      with:
        files: CHANGELOG.md
        tag_name: ${{ needs.bump.outputs.TAG_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
